root_dir: "."
method: 'gpu'
run_id: '2wiki'
algo_params:
  n_neighbors: 20
  metric: "cosine"
  batch_size: 100
  device: "mps"
emb_file: "DATA/KG/emb/emb_2wiki/passage_embs.npy"
passages_file: "DATA/KG/emb/emb_2wiki/passages.json"

