root_dir: "."
method: 'gpu'
run_id: '1'
algo_params:
  n_neighbors: 20
  metric: "cosine"
  batch_size: 100
  device: "mps"
emb_file: "DATA/KG/emb_1/passage_embs.npy"
passages_file: "DATA/KG/emb_1/evidence_passages.json"

