root_dir: "."
method: 'gpu'
run_id: '2'
algo_params:
  n_neighbors: 10
  metric: "cosine"
  batch_size: 100
  device: "mps"
emb_file: "DATA/KG/emb_2/passage_embs.npy"
passages_file: "DATA/KG/emb_2/raw_data.json"

