root_dir: '.'
seed: 2048
question_dataset: "DATA/Mistral/indexed_test_docs.json"
titled: True
init_retriever:
  name: 'tfidf'
  topk: 5
  params:
retriever:
  name: "t5"
  model: "models/mistral/mistral_quantized_8_bit"
  adapter: "models/mistral/ft_mistral_quantized_8_bit_2024-03-16_01-00-21/cp_mistral_quantized_8_bit/adapters.npz"
  model_params:
    lora_rank: 32
    lora_layers: 32
  inference_params:
    temp: 0.3
    max_token_len: 75
  T5_params:
    model_path: "models/checkpoints_t5/reason_t5-large"
    max_source_length: 512
    max_target_length: 512
  device: "mps"
KG: "DATA/KG/graph_1/graph.gpickle"
emb_model: 
  model: "sentence-transformers/multi-qa-MiniLM-L6-cos-v1"
  device: "mps"
traversal_params: 
  n_hop: 2
  n_neighbors: 5
checkpoint:
  id: "t5_agent"
  save_every: 2
  save_dir: "DATA/KG/evidence"
  resume: True
  checkpoint_path: "DATA/KG/evidence/checkpoint_t5_agent/cp_evidence.json"