root_dir: '.'
init_retriever:
  name: 'tfidf'
  topk: 5
  params:
    min_df: 1
retriever:
  name: "mistral"
  model: "models/mistral/mistral_quantized_8_bit"
  adapter: "models/mistral/ft_mistral_quantized_8_bit_2024-03-16_01-00-21/cp_mistral_quantized_8_bit/adapters.npz"
  model_params:
    lora_rank: 32
    lora_layers: 32
  inference_params:
    temp: 0.1
    max_token_len: 50
KG: "DATA/KG/graph_1/graph.gpickle"
emb_model: 
  model: "sentence-transformers/multi-qa-MiniLM-L6-cos-v1"
  device: "mps"
traversal_params: 
  n_hop: 2
  n_neighbors: 3
checkpoint:
  save_every: 5
  save_dir: "DATA/KG/evidence/checkpoints"
  resume: True
  checkpoint_path: "DATA/KG/evidence.json"